### ISSUE TITLE
Access expires for kubectl

### ISSUE THREAD

**Issue by stevesloka** [coreos/tectonic-forum#59] opened 2017-02-23 13:34 UTC
### Tectonic Version 

1.5

### Environment

Bare Metal

What hardware/cloud provider/hypervisor is being used with Tectonic?

VMWare

### Expected Behavior

Credentials downloaded to ~/.kube/config will not expire

### Actual Behavior

Credentials expire

### Reproduction Steps

  1. Sign into Console, download credentials
  2. Wait some time (few hours)
  3. kubectl can no longer authenticate and has no permissions to do anything

### Other Information

Makes this hard to refresh since my .kube/config file is rather large.

**Comment by mfburnett** [comment] 2017-02-23 18:25
Hey @stevesloka - thanks for filing this issue. I've let @ErnestG4 know; he'll get back to you in a few days and will pull in others from our team as necessary.

**Comment by ericchiang** [comment] 2017-02-24 18:06
@stevesloka yeah this is not the expected behavior. What version of kubectl are you using (`kubectl version`)?

Testing now. If there's a bug on our side we'll get it fixed by the next release.

**Comment by stevesloka** [comment] 2017-02-24 18:13
Hey @ericchiang my kubectl version is 1.5.1:

```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T
00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
```

**Comment by ericchiang** [comment] 2017-02-24 18:17
@stevesloka just spoke to an internal user seeing this same issue. I've manually reduced the expiry for tectonic-identity[0] but wasn't able to reproduce with kubectl verison 1.5.3. Since we recently backported a fix to 1.5.3 patch release I'll try with 1.5.1 and see if I get different behavior.

[0] https://github.com/coreos/dex/blob/v2.2.1/examples/config-dev.yaml#L32-L34

**Comment by stevesloka** [comment] 2017-02-24 18:22
I'm using an upstream kubectl, is there a special tectonic one?

**Comment by ericchiang** [comment] 2017-02-24 18:23
@stevesloka no. I meant an upstream patch https://github.com/kubernetes/kubernetes/pull/40191

**Comment by rjbaucells** [comment] 2017-03-01 23:19
Same issue here!

````
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-22T10:12:27Z", GoVersion:"go1.8", Compiler:"gc", Platform:"darwin/amd64"}
````

Tectonic: fresh install of 1235.12.0

**Comment by ericchiang** [comment] 2017-03-01 23:38
fyi it looks like we've identified the issue in upstream dex https://github.com/coreos/dex/issues/828

You can test this today by updating the tectonic-identity deployment to use dex v.2.2.4. Or wait for the next tectonic release over the next couple days.

**Comment by rjbaucells** [comment] 2017-03-03 00:16
I updated the tectonic-identity deployment to v.2.2.4 and it has been a day and I have not had the issue again.

**Comment by ericchiang** [comment] 2017-03-03 00:34
Perfect! Going to close this out for now. Please comment if you see the issue again.

**Closed by ericchiang** 2017-03-03 00:34 UTC
Labels: bare metal

**Comment by tpiecora** [comment] 2017-07-27 17:08
Hey I am seeing this issue 
Tectonic Version: 1.6.7-tectonic.1
 Running in AWS
Same behavior.  Every few hours I have to get a new kubeconfig from the console to keep using kubectl.

**Comment by roko-p** [comment] 2017-08-17 13:11
Same thing here, though I didn't notice it before I started using `kubectl proxy`, but it might not be connected.

Tectonic Version: `tectonic-1.6.7-tectonic.2` (tectonic-identity v2.4.1) 
Running on AWS.

Is there a workaround currently?
