### ISSUE TITLE
Tectonic-installer for AWS fails on Windows at "Submit" step

### ISSUE THREAD

**Issue by AmundsenJunior** [coreos/tectonic-forum#81] opened 2017-03-16 18:22 UTC
### Tectonic Version 
tectonic-1.5.3-tectonic.1

### Environment
Windows 10

### What hardware/cloud provider/hypervisor is being used with Tectonic?
AWS

### Expected Behavior
On "Submit" page of installer site, after all configuration steps are completed, "Submit" should succeed with creating the CloudFormation files and uploading to AWS for cluster creation.

### Actual Behavior
Once all configuration steps of the form are completed, I click on "Submit", and the button shows "Checking your Definition", then fails with the following error message:

> Failed to submit definition: error converting into Ignition: error: path not absolute error: path not absolute error: path not absolute error: path not absolute error: path not absolute error: path not absolute error: path not absolute error: path not absolute

Clicking on "Advanced Mode: Manually boot" give the same error.

In the shell, the same error outputs as:
`time="2017-03-16T14:16:19-04:00" level=error msg="&{error converting into Ignition: error: path not absolute\nerror: path not absolute\nerror: path not absolute\nerror: path not absolute\nerror: path not absolute\nerror: path not absolute\nerror: path not absolute\nerror: path not absolute Failed to submit definition: error converting into Ignition: error: path not absolute\nerror: path not absolute\nerror: path not absolute\nerror: path not absolute\nerror: path not absolute\nerror: path not absolute\nerror: path not absolute\nerror: path not absolute 400}"
`

### Other Information
I have launched the Windows tectonic-installer from git-bash and babun shells. The installer fails to launch from PowerShell or Command Prompt.

**Comment by paalkr** [comment] 2017-03-16 22:11
I would just like to mention that renaming the windows installer to installer.exe makes it run from PowerShell and command prompt. Unfortunately I cant help withe the submit error though.

**Comment by AmundsenJunior** [comment] 2017-03-17 02:11
Thanks @paalkr - I was able to launch the installer from PowerShell, but the same error on the "Submit" page occurred. Good to rule out cygwin/filesystem-path issues, though.

**Comment by mfburnett** [comment] 2017-03-20 20:40
Hi @AmundsenJunior, thanks for filing this issue. Pulling in @kbrwn, who will respond in a few days and pull in others from our team as necessary!

**Comment by kbrwn** [comment] 2017-03-20 21:09
@AmundsenJunior @paalkr This is a reproducible error with the installer on windows but we are still investigating what the issue is. 

If anyone has reproduced this linux or macos please comment here!

**Comment by ggreer** [comment] 2017-03-21 18:24
I can reproduce this issue on stock Windows 10 using the latest release of the installer & Google Chrome. Super weird.

**Comment by ggreer** [comment] 2017-03-23 20:07
This will be fixed in the next release (1.5.5-tectonic.3).

**Comment by AmundsenJunior** [comment] 2017-04-01 13:42
Thanks, @ggreer ! Should I close the issue, or will it be closed with that release?

**Comment by mfburnett** [comment] 2017-05-17 19:27
@AmundsenJunior @ggreer closing this issue, as it was resolved with 1.5.5-tectonic.3! :)

**Closed by mfburnett** 2017-05-17 19:27 UTC
Labels: aws
