### ISSUE TITLE
Scaling worker nodes on baremetal

### ISSUE THREAD

**Issue by TerraTech** [coreos/tectonic-forum#144] opened 2017-06-08 22:17 UTC
### Tectonic Version 
tectonic-1.6.2-tectonic.1
### Environment

What hardware/cloud provider/hypervisor is being used with Tectonic?

baremetal + CoreOS (1353.8.0) 

### Expected Behavior
_/etc/kubernetes/kubeconfig_ should be a file and not a directory.

### Actual Behavior
RE: #17 
While following the directions contained at: https://coreos.com/tectonic/docs/latest/admin/bare-metal-scale.html

The matchbox group files were edited and coreos was installed correctly, however the kubelet service would not start.  The problem was tracked down to _/etc/kubernetes/kubeconfig_ existed as a _directory_ instead of the proper file that contains the SSL certificate/key data.

### Reproduction Steps

  1. Reference: #17
  2. Follow directions at: https://coreos.com/tectonic/docs/latest/admin/bare-metal-scale.html
  3. PXE boot new node and let matchbox provision it
  4. Login and see if kubelet service is starting
  5. If not, see if /etc/kubernetes/kubeconfig is a directory or a file that contains the SSL certificate/key data

If you need any further information, please let me know.

Thank you!

**Comment by arianvp** [comment] 2017-06-09 08:15
I'll see if I can reproduce. I'm currently also in the process of provisioning a bare metal.

**Comment by reignblack** [comment] 2017-06-09 09:29
It looks like the documentation needs updating? As the installer is using terraform in the background

I was using just terraform for baremetal. After deploying via terraform, it will save the state of your deployment. This state is required for modifying your deployment.

To scale:
Edit the required varibles in terraform.tfvars:

tectonic_metal_worker_domains
tectonic_metal_workers_macs
tectonic_metal_workers_names
tectonic_worker_count

I then run just run terraform apply -var-file=build/my-cluster/terraform.tfvars platforms/metal

**Comment by robszumski** [comment] 2017-06-14 23:48
These docs have been updated for the 1.6.4 release. Does this address the concerns here? https://coreos.com/tectonic/docs/latest/admin/bare-metal-scale.html

**Comment by TerraTech** [comment] 2017-06-15 07:46
@robszumski I believe that _tectonic_worker_count_ applies only to cloud platforms and not to baremetal.  From a quick grep for ```module "workers"```, that module was only found in platforms aws and azure.  It seems that in baremetal, it derives the worker count from the number of elements in the array.  It would seem that just adding another node to tectonic_metal_worker_{domains,macs,names} should suffice, though I haven't had a chance to test it yet.  At least from a preliminary 'terraform plan' shows the new node being added.

**Comment by Quentin-M** [comment] 2017-06-16 00:27
Correct. The `tectonic_workers_count` is not used, as documented on https://github.com/coreos/tectonic-installer/blob/c8ab3bb55c0ab8e8bef03fe0de1491b0272440d7/Documentation/install/bare-metal/metal-terraform.md. @TerraTech is also correct on the fact that `tectonic_metal_worker_{domains,macs,names}` are the ones being used.

As for the kubeconfig, the bare-metal platform simply scp into the node these resources, including the kubeconfig (https://github.com/coreos/tectonic-installer/blob/c8ab3bb55c0ab8e8bef03fe0de1491b0272440d7/platforms/metal/remote.tf).

**Comment by robszumski** [comment] 2017-06-20 18:00
@TerraTech Does @Quentin-M's response make sense to you? Can I close this out?

**Closed** 2017-07-04 06:23 UTC

**Comment by rushins** [comment] 2017-11-07 15:40
i have run into several issues scaling new nodes. did anyone successfully made scale working on cluster with 1.6 or 1.7 ?

**Comment by rushins** [comment] 2017-11-12 01:00
i ran into issue wiht 1.7.3 scaling node. did anyone tried.

**Comment by MartijnStraatman** [comment] 2018-03-07 18:34
Same problem here on 1.8.4_2. The installer won't scp the kubeconfig to the extra worker
